Backend : 
    MOCK : 
        getTransfers : InfinityTransactionServices.getUserTransaction
        getInstructions : InfinityTransactionServices.getUserTransaction
        getUpcomingTransactions : InfinityTransactionServices.getUserScheduledTransactions
        getBankDates : InfinityTransactionServices.getBankDates
    T24 : 
        getTransfers : T24ISPaymentsView.getPastTransactions
        getInstructions : T24ISPaymentsView.getUserScheduledTransactions
        getUpcomingTransactions : PaymentOrchestrationServices.upcomingTransactions
        getBankDates : T24ISPaymentsView.getBankDates
    SRMS : 
        getTransfers : SRMSTransactionsJavaService.GetPastTransactionsFromSRMS
        getInstructions : T24ISPaymentsView.getUserScheduledTransactions
        getUpcomingTransactions : PaymentOrchestrationServices.upcomingTransactions
        getBankDates : T24ISPaymentsView.getBankDates
    SRMS_MOCK :
        getTransfers: SRMSTransactionsJavaService.GetPastTransactionsFromSRMS
        getInstructions: SRMSMockIntegrationService.GetSRMSTransactionsFromDBX
        getUpcomingTransactions: InfinityTransactionServices.getUserTransaction
        getBankDates: TransfersMockData.getBankDates