package com.temenos.dbx.party.utils;

public class PartyConstants {
    public static final String COMMUNICATION_TYPE = "CommunicationType";
    public static final String TYPE_NATURE = "typeNature";
    public static final String REFERENCES = "references";
    public static final String MOBILE = "Mobile";
    public static final String PARTY = "PARTY";
    public static final String EMAIL = "Email";
    public static final String BackOfficeIdentifier = "BackOfficeIdentifier";
    public static final String TransactT24 = "TransactT24";
    public static String partyType = "partyType";
    public static String partyStatus = "partyStatus";
    public static String firstName = "firstName";
    public static String lastName = "lastName";
    public static String addresses = "addresses";
    public static String contactAddress = "contactAddress";
    public static String electronicAddress = "electronicAddress";
    public static String phoneAddress = "phoneAddress";
    public static String partyId = "partyId";
    public static String partyRelations = "partyRelations";
    public static String relationType = "relationType";
    public static String hierarchyType = "hierarchyType";
    public static String addressesReference = "addressesReference";
    public static String communicationNature = "communicationNature";
    public static String MailingAddress = "MailingAddress";
    public static String Home = "Home";
    public static String Physical = "Physical";
    public static String Phone = "Phone";
    public static String Electronic = "Electronic";
    public static String identifierNumber = "identifierNumber";
    public static String identifierType = "identifierType";
    public static String alternateIdentifierNumber = "alternateIdentifierNumber";
    public static String alternateIdentifierType = "alternateIdentifierType";
    public static String dateOfBirth = "dateOfBirth";
    public static String contactNumber = "contactNumber";
    public static String entityName = "entityName";
    public static String emailId = "emailId";
    public static String recordCount = "recordCount";
    public static String parties = "parties";
    public static String id = "id";
    public static String alternateIdentities="alternateIdentities";
    public static String identityType = "identityType";
    public static String identityNumber = "identityNumber";
    public static String coreCustomerId = "coreCustomerId";
    public static String identitySource = "identitySource";
    public static String isEnrolled = "isEnrolled";
    
    public static String PARTY_TYPE_INDIVIDUAL = "Individual";
    public static String classifications = "classifications";
	public static String classificationCode = "classificationCode";
	public static String name = "name";
	public static String ClassificationCode = "ClassificationCode";
	public static String description = "description";
}
