/*******************************************************************************
 * Copyright © Temenos Headquarters SA 2023. All rights reserved.
 ******************************************************************************/
package com.temenos.infinity.tradesupplyfinance.config;

/**
 * @author k.meiyazhagan
 */
public enum TradeSupplyFinanceAlerts {

    TSF_RECEIVABLE_SINGLE_BILL_APPROVED("TSF_RECEIVABLE_SINGLE_BILLS", "TSF_RECEIVABLE_SINGLE_BILL_APPROVED"),
    TSF_RECEIVABLE_SINGLE_BILL_CANCELLATION_APPROVED("TSF_RECEIVABLE_SINGLE_BILLS", "TSF_RECEIVABLE_SINGLE_BILL_CANCELLATION_APPROVED"),
    TSF_RECEIVABLE_SINGLE_BILL_CANCELLATION_REJECTED("TSF_RECEIVABLE_SINGLE_BILLS", "TSF_RECEIVABLE_SINGLE_BILL_CANCELLATION_REJECTED"),
    TSF_RECEIVABLE_SINGLE_BILL_CANCELLATION_SUBMITTED("TSF_RECEIVABLE_SINGLE_BILLS", "TSF_RECEIVABLE_SINGLE_BILL_CANCELLATION_SUBMITTED"),
    TSF_RECEIVABLE_SINGLE_BILL_CANCELLED("TSF_RECEIVABLE_SINGLE_BILLS", "TSF_RECEIVABLE_SINGLE_BILL_CANCELLED"),
    TSF_RECEIVABLE_SINGLE_BILL_DELETED("TSF_RECEIVABLE_SINGLE_BILLS", "TSF_RECEIVABLE_SINGLE_BILL_DELETED"),
    TSF_RECEIVABLE_SINGLE_BILL_FINANCED("TSF_RECEIVABLE_SINGLE_BILLS", "TSF_RECEIVABLE_SINGLE_BILL_FINANCED"),
    TSF_RECEIVABLE_SINGLE_BILL_FINANCE_REQUESTED("TSF_RECEIVABLE_SINGLE_BILLS", "TSF_RECEIVABLE_SINGLE_BILL_FINANCE_REQUESTED"),
    TSF_RECEIVABLE_SINGLE_BILL_IMPORTED_BILLS_SUBMITTED("TSF_RECEIVABLE_SINGLE_BILLS", "TSF_RECEIVABLE_SINGLE_BILL_IMPORTED_BILLS_SUBMITTED"),
    TSF_RECEIVABLE_SINGLE_BILL_IMPORT_DELETED("TSF_RECEIVABLE_SINGLE_BILLS", "TSF_RECEIVABLE_SINGLE_BILL_IMPORT_DELETED"),
    TSF_RECEIVABLE_SINGLE_BILL_IMPORT_DONE("TSF_RECEIVABLE_SINGLE_BILLS", "TSF_RECEIVABLE_SINGLE_BILL_IMPORT_DONE"),
    TSF_RECEIVABLE_SINGLE_BILL_IMPORT_FAILED("TSF_RECEIVABLE_SINGLE_BILLS", "TSF_RECEIVABLE_SINGLE_BILL_IMPORT_FAILED"),
    TSF_RECEIVABLE_SINGLE_BILL_REJECTED("TSF_RECEIVABLE_SINGLE_BILLS", "TSF_RECEIVABLE_SINGLE_BILL_REJECTED"),
    TSF_RECEIVABLE_SINGLE_BILL_RETURNED_BY_BANK("TSF_RECEIVABLE_SINGLE_BILLS", "TSF_RECEIVABLE_SINGLE_BILL_RETURNED_BY_BANK"),
    TSF_RECEIVABLE_SINGLE_BILL_REVISION_SUBMITTED("TSF_RECEIVABLE_SINGLE_BILLS", "TSF_RECEIVABLE_SINGLE_BILL_REVISION_SUBMITTED"),
    TSF_RECEIVABLE_SINGLE_BILL_SETTLED("TSF_RECEIVABLE_SINGLE_BILLS", "TSF_RECEIVABLE_SINGLE_BILL_SETTLED"),
    TSF_RECEIVABLE_SINGLE_BILL_SUBMITTED("TSF_RECEIVABLE_SINGLE_BILLS", "TSF_RECEIVABLE_SINGLE_BILL_SUBMITTED");

    private final String type;
    private final String subType;

    TradeSupplyFinanceAlerts(String type, String subType) {
        this.type = type;
        this.subType = subType;
    }

    public String getType() {
        return this.type;
    }

    public String getSubType() {
        return this.subType;
    }
}
