package com.temenos.dbx.constants;

public enum ActionConstant {
	RDC,
	INTERNATIONAL_ACCOUNT_FUND_TRANSFER_CREATE,
	INTER_BANK_ACCOUNT_FUND_TRANSFER_CREATE,
	INTRA_BANK_FUND_TRANSFER_CREATE,
	TRANSFER_BETWEEN_OWN_ACCOUNT_CREATE,
	BILL_PAY_BULK,
	BILL_PAY_CREATE,
	DOMESTIC_WIRE_TRANSFER_CREATE,
	INTERNATIONAL_WIRE_TRANSFER_CREATE,
	P2P_CREATE,
	DOMESTIC_WIRE_TRANSFER_DELETE_RECEPIENT,
	INTERNATIONAL_ACCOUNT_FUND_TRANSFER_DELETE_RECEPIENT,
	INTERNATIONAL_WIRE_TRANSFER_DELETE_RECEPIENT,
	INTER_BANK_ACCOUNT_FUND_TRANSFER_DELETE_RECEPIENT,
	INTRA_BANK_FUND_TRANSFER_DELETE_RECEPIENT,
	TRANSFER_BETWEEN_OWN_ACCOUNT_DELETE_RECEPIENT,
	DOMESTIC_WIRE_TRANSFER_VIEW,
	INTERNATIONAL_WIRE_TRANSFER_VIEW,
	TRANSFER_BETWEEN_OWN_ACCOUNT_VIEW,
	INTER_BANK_ACCOUNT_FUND_TRANSFER_VIEW,
	INTRA_BANK_FUND_TRANSFER_VIEW,
	INTERNATIONAL_ACCOUNT_FUND_TRANSFER_VIEW,
	DISPUTE_TRANSACTIONS_VIEW,
	BILL_PAY_VIEW_PAYMENTS,
	P2P_VIEW,
	STOP_PAYMENT_REQUEST_CREATE,
	REVOKE_STOP_PAYMENT_REQUEST_CREATE,
	UNKNOWN;
	
	public static ActionConstant getActionConstant(String actionName) {
		try {
			return ActionConstant.valueOf(actionName);
		}catch(Exception e) {
			return ActionConstant.UNKNOWN;
		}
	}
}
