/*******************************************************************************
 * Copyright © Temenos Headquarters SA 2023. All rights reserved.
 ******************************************************************************/
package com.temenos.infinity.tradefinanceservices.utils;

/**
 * @author k.meiyazhagan
 */
public enum AlertsEnum {
    IMPORT_LC_APPROVED("TRADEFINANCE_IMPORTLC", "IMPORT_LC_APPROVED"),
    IMPORT_LC_CREATED("TRADEFINANCE_IMPORTLC", "IMPORT_LC_CREATED"),
    IMPORT_LC_REJECTED("TRADEFINANCE_IMPORTLC", "IMPORT_LC_REJECTED"),
    IMPORT_LC_SUBMITTED_APPROVAL("TRADEFINANCE_IMPORTLC", "IMPORT_LC_SUBMITTED_APPROVAL"),
    IMPORT_LC_AMENDMENT_APPROVED("TRADEFINANCE_IMPORTLC_AMENDMENTS", "IMPORT_LC_AMENDMENT_APPROVED"),
    IMPORT_LC_AMENDMENT_DOCUMENTS_APPROVED("TRADEFINANCE_IMPORTLC_AMENDMENTS", "IMPORT_LC_AMENDMENT_DOCUMENTS_APPROVED"),
    IMPORT_LC_AMENDMENT_DOCUMENTS_REJECTED("TRADEFINANCE_IMPORTLC_AMENDMENTS", "IMPORT_LC_AMENDMENT_DOCUMENTS_REJECTED"),
    IMPORT_LC_AMENDMENT_PENDING_WITH_BANK_FOR_APPROVAL("TRADEFINANCE_IMPORTLC_AMENDMENTS", "IMPORT_LC_AMENDMENT_PENDING_WITH_BANK_FOR_APPROVAL"),
    IMPORT_LC_AMENDMENT_REJECTED("TRADEFINANCE_IMPORTLC_AMENDMENTS", "IMPORT_LC_AMENDMENT_REJECTED"),
    IMPORT_LC_AMENDMENT_SUBMITTED_FOR_APPROVAL("TRADEFINANCE_IMPORTLC_AMENDMENTS", "IMPORT_LC_AMENDMENT_SUBMITTED_FOR_APPROVAL"),
    IMPORT_LC_AMENDMENT_SUBMITTED_FOR_BANK_APPROVAL("TRADEFINANCE_IMPORTLC_AMENDMENTS", "IMPORT_LC_AMENDMENT_SUBMITTED_FOR_BANK_APPROVAL"),
    IMPORT_LC_AMENDMENT_SUBMITTED_WITH_SELFCONSENT("TRADEFINANCE_IMPORTLC_AMENDMENTS", "IMPORT_LC_AMENDMENT_SUBMITTED_WITH_SELFCONSENT"),
    IMPORT_LC_DRAWING_APPROVED("TRADEFINANCE_IMPORTLC_DRAWINGS", "IMPORT_LC_DRAWING_APPROVED"),
    IMPORT_LC_DRAWING_REJECTED("TRADEFINANCE_IMPORTLC_DRAWINGS", "IMPORT_LC_DRAWING_REJECTED"),
    IMPORT_LC_DRAWING_SUBMITTED("TRADEFINANCE_IMPORTLC_DRAWINGS", "IMPORT_LC_DRAWING_SUBMITTED"),
    EXPORT_LC_BENEFICIARY_CONSENT_SUBMITTED("TRADEFINANCE_EXPORTLC", "EXPORT_LC_BENEFICIARY_CONSENT_SUBMITTED"),
    EXPORT_LC_AMENDMENT_DOCUMENTS_APPROVED("TRADEFINANCE_EXPORTLC_AMENDMENTS", "EXPORT_LC_AMENDMENT_DOCUMENTS_APPROVED"),
    EXPORT_LC_AMENDMENT_DOCUMENTS_REJECTED("TRADEFINANCE_EXPORTLC_AMENDMENTS", "EXPORT_LC_AMENDMENT_DOCUMENTS_REJECTED"),
    EXPORT_LC_AMENDMENT_SUBMITTED_FOR_APPROVAL("TRADEFINANCE_EXPORTLC_AMENDMENTS", "EXPORT_LC_AMENDMENT_SUBMITTED_FOR_APPROVAL"),
    EXPORT_LC_AMENDMENT_SUBMITTED_WITH_SELFCONSENT("TRADEFINANCE_EXPORTLC_AMENDMENTS", "EXPORT_LC_AMENDMENT_SUBMITTED_WITH_SELFCONSENT"),
    EXPORT_LC_DRAWING_APPROVED("TRADEFINANCE_EXPORTLC_DRAWINGS", "EXPORT_LC_DRAWING_APPROVED"),
    EXPORT_LC_DRAWING_REJECTED("TRADEFINANCE_EXPORTLC_DRAWINGS", "EXPORT_LC_DRAWING_REJECTED"),
    EXPORT_LC_DRAWING_SUBMITTED("TRADEFINANCE_EXPORTLC_DRAWINGS", "EXPORT_LC_DRAWING_SUBMITTED"),

    GUARANTEES_ISSUED_APPROVED("TRADEFINANCE_GUARANTEES_ISSUED", "GUARANTEES_ISSUED_APPROVED"),
    GUARANTEES_ISSUED_REJECTED("TRADEFINANCE_GUARANTEES_ISSUED", "GUARANTEES_ISSUED_REJECTED"),
    GUARANTEES_ISSUED_RETURNED_BY_BANK("TRADEFINANCE_GUARANTEES_ISSUED", "GUARANTEES_ISSUED_RETURNED_BY_BANK"),
    GUARANTEES_ISSUED_SUBMITTED("TRADEFINANCE_GUARANTEES_ISSUED", "GUARANTEES_ISSUED_SUBMITTED"),
    GUARANTEES_ISSUED_AMENDMENT_APPROVED("TRADEFINANCE_GUARANTEES_ISSUED_AMENDMENTS", "GUARANTEES_ISSUED_AMENDMENT_APPROVED"),
    GUARANTEES_ISSUED_AMENDMENT_PENDING_WITH_BANK_FOR_APPROVAL("TRADEFINANCE_GUARANTEES_ISSUED_AMENDMENTS", "GUARANTEES_ISSUED_AMENDMENT_PENDING_WITH_BANK_FOR_APPROVAL"),
    GUARANTEES_ISSUED_AMENDMENT_REJECTED("TRADEFINANCE_GUARANTEES_ISSUED_AMENDMENTS", "GUARANTEES_ISSUED_AMENDMENT_REJECTED"),
    GUARANTEES_ISSUED_AMENDMENT_SUBMITTED_FOR_APPROVAL("TRADEFINANCE_GUARANTEES_ISSUED_AMENDMENTS", "GUARANTEES_ISSUED_AMENDMENT_SUBMITTED_FOR_APPROVAL"),
    GUARANTEES_ISSUED_AMENDMENT_SUBMITTED_WITH_SELFCONSENT("TRADEFINANCE_GUARANTEES_ISSUED_AMENDMENTS", "GUARANTEES_ISSUED_AMENDMENT_SUBMITTED_WITH_SELFCONSENT"),
    GUARANTEES_ISSUED_CLAIM_ACCEPTED("TRADEFINANCE_GUARANTEES_ISSUED_CLAIMS", "GUARANTEES_ISSUED_CLAIM_ACCEPTED"),
    GUARANTEES_ISSUED_CLAIM_CONSENT_REJECTED("TRADEFINANCE_GUARANTEES_ISSUED_CLAIMS", "GUARANTEES_ISSUED_CLAIM_CONSENT_REJECTED"),
    GUARANTEES_ISSUED_CLAIM_EXTENDED_FOR_PAYMENT("TRADEFINANCE_GUARANTEES_ISSUED_CLAIMS", "GUARANTEES_ISSUED_CLAIM_EXTENDED_FOR_PAYMENT"),
    GUARANTEES_ISSUED_CLAIM_HONOURED("TRADEFINANCE_GUARANTEES_ISSUED_CLAIMS", "GUARANTEES_ISSUED_CLAIM_HONOURED"),
    GUARANTEES_ISSUED_CLAIM_HONOURED_BY_BANK_PENDING_CONSENT_BY_APPLICANT("TRADEFINANCE_GUARANTEES_ISSUED_CLAIMS", "GUARANTEES_ISSUED_CLAIM_HONOURED_BY_BANK_PENDING_CONSENT_BY_APPLICANT"),
    GUARANTEES_ISSUED_CLAIM_HONOURED_BY_BANK_REJECTED_BY_APPLICANT("TRADEFINANCE_GUARANTEES_ISSUED_CLAIMS", "GUARANTEES_ISSUED_CLAIM_HONOURED_BY_BANK_REJECTED_BY_APPLICANT"),
    GUARANTEES_ISSUED_CLAIM_PRESENTATION_ACCEPTED("TRADEFINANCE_GUARANTEES_ISSUED_CLAIMS", "GUARANTEES_ISSUED_CLAIM_PRESENTATION_ACCEPTED"),
    GUARANTEES_ISSUED_CLAIM_PRESENTATION_ACCEPTED_AND_SETTLED("TRADEFINANCE_GUARANTEES_ISSUED_CLAIMS", "GUARANTEES_ISSUED_CLAIM_PRESENTATION_ACCEPTED_AND_SETTLED"),
    GUARANTEES_ISSUED_CLAIM_PRESENTATION_ACCEPTED_AND_SETTLEMENT_EXTENDED("TRADEFINANCE_GUARANTEES_ISSUED_CLAIMS", "GUARANTEES_ISSUED_CLAIM_PRESENTATION_ACCEPTED_AND_SETTLEMENT_EXTENDED"),
    GUARANTEES_ISSUED_CLAIM_PRESENTATION_REJECTED("TRADEFINANCE_GUARANTEES_ISSUED_CLAIMS", "GUARANTEES_ISSUED_CLAIM_PRESENTATION_REJECTED"),
    GUARANTEES_ISSUED_CLAIM_PRESENTATION_SUBMITTED("TRADEFINANCE_GUARANTEES_ISSUED_CLAIMS", "GUARANTEES_ISSUED_CLAIM_PRESENTATION_SUBMITTED"),
    GUARANTEES_ISSUED_CLAIM_PROCESSING("TRADEFINANCE_GUARANTEES_ISSUED_CLAIMS", "GUARANTEES_ISSUED_CLAIM_PROCESSING"),
    GUARANTEES_ISSUED_CLAIM_REJECTED("TRADEFINANCE_GUARANTEES_ISSUED_CLAIMS", "GUARANTEES_ISSUED_CLAIM_REJECTED"),
    GUARANTEES_ISSUED_CLAIM_RETURNED("TRADEFINANCE_GUARANTEES_ISSUED_CLAIMS", "GUARANTEES_ISSUED_CLAIM_RETURNED"),
    GUARANTEES_ISSUED_CLAIM_SUBMITTED("TRADEFINANCE_GUARANTEES_ISSUED_CLAIMS", "GUARANTEES_ISSUED_CLAIM_SUBMITTED"),
    GUARANTEES_RECEIVED_ACCEPTED("TRADEFINANCE_GUARANTEES_RECEIVED", "GUARANTEES_RECEIVED_ACCEPTED"),
    GUARANTEES_RECEIVED_APPROVED("TRADEFINANCE_GUARANTEES_RECEIVED", "GUARANTEES_RECEIVED_APPROVED"),
    GUARANTEES_RECEIVED_PENDING("TRADEFINANCE_GUARANTEES_RECEIVED", "GUARANTEES_RECEIVED_PENDING"),
    GUARANTEES_RECEIVED_REJECETED("TRADEFINANCE_GUARANTEES_RECEIVED", "GUARANTEES_RECEIVED_REJECETED"),
    GUARANTEES_RECEIVED_SUBMITTED("TRADEFINANCE_GUARANTEES_RECEIVED", "GUARANTEES_RECEIVED_SUBMITTED"),
    GUARANTEES_RECEIVED_AMENDMENT_ACCEPTED("TRADEFINANCE_GUARANTEES_RECEIVED_AMENDMENTS", "GUARANTEES_RECEIVED_AMENDMENT_ACCEPTED"),
    GUARANTEES_RECEIVED_AMENDMENT_APPROVED("TRADEFINANCE_GUARANTEES_RECEIVED_AMENDMENTS", "GUARANTEES_RECEIVED_AMENDMENT_APPROVED"),
    GUARANTEES_RECEIVED_AMENDMENT_PENDING("TRADEFINANCE_GUARANTEES_RECEIVED_AMENDMENTS", "GUARANTEES_RECEIVED_AMENDMENT_PENDING"),
    GUARANTEES_RECEIVED_AMENDMENT_REJECTED("TRADEFINANCE_GUARANTEES_RECEIVED_AMENDMENTS", "GUARANTEES_RECEIVED_AMENDMENT_REJECTED"),
    GUARANTEES_RECEIVED_AMENDMENT_SUBMITTED("TRADEFINANCE_GUARANTEES_RECEIVED_AMENDMENTS", "GUARANTEES_RECEIVED_AMENDMENT_SUBMITTED"),
    GUARANTEES_RECEIVED_CLAIM_ACCEPTED_AND_CLAIM_HONOURED("TRADEFINANCE_GUARANTEES_RECEIVED_CLAIMS", "GUARANTEES_RECEIVED_CLAIM_ACCEPTED_AND_CLAIM_HONOURED"),
    GUARANTEES_RECEIVED_CLAIM_ACTIVE("TRADEFINANCE_GUARANTEES_RECEIVED_CLAIMS", "GUARANTEES_RECEIVED_CLAIM_ACTIVE"),
    GUARANTEES_RECEIVED_CLAIM_APPROVED("TRADEFINANCE_GUARANTEES_RECEIVED_CLAIMS", "GUARANTEES_RECEIVED_CLAIM_APPROVED"),
    GUARANTEES_RECEIVED_CLAIM_DECLINED_AND_CLOSED("TRADEFINANCE_GUARANTEES_RECEIVED_CLAIMS", "GUARANTEES_RECEIVED_CLAIM_DECLINED_AND_CLOSED"),
    GUARANTEES_RECEIVED_CLAIM_DOCUMENT_RESUBMITTED_FOR_APPROVAL("TRADEFINANCE_GUARANTEES_RECEIVED_CLAIMS", "GUARANTEES_RECEIVED_CLAIM_DOCUMENT_RESUBMITTED_FOR_APPROVAL"),
    GUARANTEES_RECEIVED_CLAIM_DOCUMENT_RESUBMITTED_WAS_ACCEPTED("TRADEFINANCE_GUARANTEES_RECEIVED_CLAIMS", "GUARANTEES_RECEIVED_CLAIM_DOCUMENT_RESUBMITTED_WAS_ACCEPTED"),
    GUARANTEES_RECEIVED_CLAIM_DOCUMENT_RESUBMITTED_WAS_REJECTED("TRADEFINANCE_GUARANTEES_RECEIVED_CLAIMS", "GUARANTEES_RECEIVED_CLAIM_DOCUMENT_RESUBMITTED_WAS_REJECTED"),
    GUARANTEES_RECEIVED_CLAIM_DOCUMENT_SUBMITTED_FOR_APPROVAL("TRADEFINANCE_GUARANTEES_RECEIVED_CLAIMS", "GUARANTEES_RECEIVED_CLAIM_DOCUMENT_SUBMITTED_FOR_APPROVAL"),
    GUARANTEES_RECEIVED_CLAIM_DOCUMENT_SUBMITTED_WAS_APPROVED("TRADEFINANCE_GUARANTEES_RECEIVED_CLAIMS", "GUARANTEES_RECEIVED_CLAIM_DOCUMENT_SUBMITTED_WAS_APPROVED"),
    GUARANTEES_RECEIVED_CLAIM_DOCUMENT_SUBMITTED_WAS_REJECTED("TRADEFINANCE_GUARANTEES_RECEIVED_CLAIMS", "GUARANTEES_RECEIVED_CLAIM_DOCUMENT_SUBMITTED_WAS_REJECTED"),
    GUARANTEES_RECEIVED_CLAIM_INACTIVE("TRADEFINANCE_GUARANTEES_RECEIVED_CLAIMS", "GUARANTEES_RECEIVED_CLAIM_INACTIVE"),
    GUARANTEES_RECEIVED_CLAIM_PENDING("TRADEFINANCE_GUARANTEES_RECEIVED_CLAIMS", "GUARANTEES_RECEIVED_CLAIM_PENDING"),
    GUARANTEES_RECEIVED_CLAIM_SUBMITTED("TRADEFINANCE_GUARANTEES_RECEIVED_CLAIMS", "GUARANTEES_RECEIVED_CLAIM_SUBMITTED"),

    INWARD_COLLECTION_APPROVED("TRADEFINANCE_INWARD_COLLECTIONS", "INWARD_COLLECTION_APPROVED"),
    INWARD_COLLECTION_CANCELLED("TRADEFINANCE_INWARD_COLLECTIONS", "INWARD_COLLECTION_CANCELLED"),
    INWARD_COLLECTION_CONSENT_SUBMITTED("TRADEFINANCE_INWARD_COLLECTIONS", "INWARD_COLLECTION_CONSENT_SUBMITTED"),
    INWARD_COLLECTION_PAYDUE("TRADEFINANCE_INWARD_COLLECTIONS", "INWARD_COLLECTION_PAYDUE"),
    INWARD_COLLECTION_PAYDUE_LAST_FIVE_DAYS("TRADEFINANCE_INWARD_COLLECTIONS", "INWARD_COLLECTION_PAYDUE_LAST_FIVE_DAYS"),
    INWARD_COLLECTION_PAYDUE_ON_LAST_DAY("TRADEFINANCE_INWARD_COLLECTIONS", "INWARD_COLLECTION_PAYDUE_ON_LAST_DAY"),
    INWARD_COLLECTION_PAYDUE_ON_LAST_THREE_ODD_DAYS("TRADEFINANCE_INWARD_COLLECTIONS", "INWARD_COLLECTION_PAYDUE_ON_LAST_THREE_ODD_DAYS"),
    INWARD_COLLECTION_PAYDUE_OR_OVERDUE("TRADEFINANCE_INWARD_COLLECTIONS", "INWARD_COLLECTION_PAYDUE_OR_OVERDUE"),
    INWARD_COLLECTION_PAYMENT_INITIATION_SUBMITTED("TRADEFINANCE_INWARD_COLLECTIONS", "INWARD_COLLECTION_PAYMENT_INITIATION_SUBMITTED"),
    INWARD_COLLECTION_PROCESSING("TRADEFINANCE_INWARD_COLLECTIONS", "INWARD_COLLECTION_PROCESSING"),
    INWARD_COLLECTION_REJECTED("TRADEFINANCE_INWARD_COLLECTIONS", "INWARD_COLLECTION_REJECTED"),
    INWARD_COLLECTION_REQUEST_RESUBMITTED("TRADEFINANCE_INWARD_COLLECTIONS", "INWARD_COLLECTION_REQUEST_RESUBMITTED"),
    INWARD_COLLECTION_REQUEST_RESUBMITTED_ACCEPTED("TRADEFINANCE_INWARD_COLLECTIONS", "INWARD_COLLECTION_REQUEST_RESUBMITTED_ACCEPTED"),
    INWARD_COLLECTION_REQUEST_RESUBMITTED_REJECTED("TRADEFINANCE_INWARD_COLLECTIONS", "INWARD_COLLECTION_REQUEST_RESUBMITTED_REJECTED"),
    INWARD_COLLECTION_RETURNED("TRADEFINANCE_INWARD_COLLECTIONS", "INWARD_COLLECTION_RETURNED"),
    INWARD_COLLECTION_SETTLED("TRADEFINANCE_INWARD_COLLECTIONS", "INWARD_COLLECTION_SETTLED"),
    INWARD_COLLECTION_SETTLED_FROM_PAYDUE("TRADEFINANCE_INWARD_COLLECTIONS", "INWARD_COLLECTION_SETTLED_FROM_PAYDUE"),
    INWARD_COLLECTION_SUBMITTED("TRADEFINANCE_INWARD_COLLECTIONS", "INWARD_COLLECTION_SUBMITTED"),
    INWARD_COLLECTION_USANCE_ACCEPTANCE_SUBMITTED("TRADEFINANCE_INWARD_COLLECTIONS", "INWARD_COLLECTION_USANCE_ACCEPTANCE_SUBMITTED"),
    INWARD_COLLECTION_AMENDMENT_CANCEL_REQUEST_ACCEPTED("TRADEFINANCE_INWARD_COLLECTION_AMENDMENTS", "INWARD_COLLECTION_AMENDMENT_CANCEL_REQUEST_ACCEPTED"),
    INWARD_COLLECTION_AMENDMENT_CANCEL_REQUEST_REJECTED("TRADEFINANCE_INWARD_COLLECTION_AMENDMENTS", "INWARD_COLLECTION_AMENDMENT_CANCEL_REQUEST_REJECTED"),
    INWARD_COLLECTION_AMENDMENT_CANCEL_REQUEST_SUBMITTED("TRADEFINANCE_INWARD_COLLECTION_AMENDMENTS", "INWARD_COLLECTION_AMENDMENT_CANCEL_REQUEST_SUBMITTED"),
    INWARD_COLLECTION_AMENDMENT_CONSENT_SUBMITTED("TRADEFINANCE_INWARD_COLLECTION_AMENDMENTS", "INWARD_COLLECTION_AMENDMENT_CONSENT_SUBMITTED"),
    OUTWARD_COLLECTION_DOCUMENT_RESUBMITTED("TRADEFINANCE_OUTWARD_COLLECTIONS", "OUTWARD_COLLECTION_DOCUMENT_RESUBMITTED"),
    OUTWARD_COLLECTION_DOCUMENT_SUBMITTED("TRADEFINANCE_OUTWARD_COLLECTIONS", "OUTWARD_COLLECTION_DOCUMENT_SUBMITTED"),
    OUTWARD_COLLECTION_OVERDUE("TRADEFINANCE_OUTWARD_COLLECTIONS", "OUTWARD_COLLECTION_OVERDUE"),
    OUTWARD_COLLECTION_RESUBMITTED_DOCUMENT_ACCEPTED("TRADEFINANCE_OUTWARD_COLLECTIONS", "OUTWARD_COLLECTION_RESUBMITTED_DOCUMENT_ACCEPTED"),
    OUTWARD_COLLECTION_RESUBMITTED_DOCUMENT_REJECTED("TRADEFINANCE_OUTWARD_COLLECTIONS", "OUTWARD_COLLECTION_RESUBMITTED_DOCUMENT_REJECTED"),
    OUTWARD_COLLECTION_SUBMITTED_DOCUMENT_APPROVED("TRADEFINANCE_OUTWARD_COLLECTIONS", "OUTWARD_COLLECTION_SUBMITTED_DOCUMENT_APPROVED"),
    OUTWARD_COLLECTION_SUBMITTED_DOCUMENT_REJECTED("TRADEFINANCE_OUTWARD_COLLECTIONS", "OUTWARD_COLLECTION_SUBMITTED_DOCUMENT_REJECTED"),
    OUTWARD_COLLECTION_AMENDMENT_ACCEPTED("TRADEFINANCE_OUTWARD_COLLECTION_AMENDMENTS", "OUTWARD_COLLECTION_AMENDMENT_ACCEPTED"),
    OUTWARD_COLLECTION_AMENDMENT_PROCESSING("TRADEFINANCE_OUTWARD_COLLECTION_AMENDMENTS", "OUTWARD_COLLECTION_AMENDMENT_PROCESSING"),
    OUTWARD_COLLECTION_AMENDMENT_REJECTED("TRADEFINANCE_OUTWARD_COLLECTION_AMENDMENTS", "OUTWARD_COLLECTION_AMENDMENT_REJECTED"),
    OUTWARD_COLLECTION_AMENDMENT_REQUEST_SUBMITTED("TRADEFINANCE_OUTWARD_COLLECTION_AMENDMENTS", "OUTWARD_COLLECTION_AMENDMENT_REQUEST_SUBMITTED"),
    OUTWARD_COLLECTION_AMENDMENT_RETURNED("TRADEFINANCE_OUTWARD_COLLECTION_AMENDMENTS", "OUTWARD_COLLECTION_AMENDMENT_RETURNED"),
    OUTWARD_COLLECTION_REVISED_AMENDMENT_REQUEST_SUBMITTED("TRADEFINANCE_OUTWARD_COLLECTION_AMENDMENTS", "OUTWARD_COLLECTION_REVISED_AMENDMENT_REQUEST_SUBMITTED");

    private final String type;
    private final String subType;

    AlertsEnum(String type, String subType) {
        this.type = type;
        this.subType = subType;
    }

    public String getType() {
        return this.type;
    }

    public String getSubType() {
        return this.subType;
    }
}
