package com.temenos.dbx.eum.product.constants;

public final class FeatureAction {
	
	public static final String BILL_PAY_CREATE = "BILL_PAY_CREATE";
	public static final String INTER_BANK_ACCOUNT_FUND_TRANSFER_CREATE = "INTER_BANK_ACCOUNT_FUND_TRANSFER_CREATE";
	public static final String INTRA_BANK_FUND_TRANSFER_CREATE = "INTRA_BANK_FUND_TRANSFER_CREATE";
	public static final String TRANSFER_BETWEEN_OWN_ACCOUNT_CREATE = "TRANSFER_BETWEEN_OWN_ACCOUNT_CREATE";
	public static final String P2P_CREATE = "P2P_CREATE";
	public static final String P2P_VIEW_RECEPIENT = "P2P_VIEW_RECEPIENT";	
	public static final String DOMESTIC_WIRE_TRANSFER_CREATE = "DOMESTIC_WIRE_TRANSFER_CREATE";
	public static final String INTERNATIONAL_ACCOUNT_FUND_TRANSFER_CREATE = "INTERNATIONAL_ACCOUNT_FUND_TRANSFER_CREATE";
	public static final String INTERNATIONAL_WIRE_TRANSFER_CREATE = "INTERNATIONAL_WIRE_TRANSFER_CREATE";
	public static final String ACH_COLLECTION_CREATE = "ACH_COLLECTION_CREATE";
	public static final String ACH_PAYMENT_CREATE = "ACH_PAYMENT_CREATE";
	public static final String ACH_COLLECTION_CREATE_TEMPLATE = "ACH_COLLECTION_CREATE_TEMPLATE";
	public static final String ACH_PAYMENT_CREATE_TEMPLATE = "ACH_PAYMENT_CREATE_TEMPLATE";	
	public static final String ACH_COLLECTION_DELETE_TEMPLATE  = "ACH_COLLECTION_DELETE_TEMPLATE";
	public static final String ACH_COLLECTION_EDIT_TEMPLATE  = "ACH_COLLECTION_EDIT_TEMPLATE";
	public static final String ACH_PAYMENT_EDIT_TEMPLATE = "ACH_PAYMENT_EDIT_TEMPLATE";	
	public static final String ACH_PAYMENT_DELETE_TEMPLATE  = "ACH_PAYMENT_DELETE_TEMPLATE";
	public static final String DOMESTIC_WIRE_TRANSFER_BULKWIRES  ="DOMESTIC_WIRE_TRANSFER_BULKWIRES";
	public static final String INTERNATIONAL_WIRE_TRANSFER_BULKWIRES = "INTERNATIONAL_WIRE_TRANSFER_BULKWIRES";
	public static final String APPROVAL_MATRIX_MANAGE = "APPROVAL_MATRIX_MANAGE";
	public static final String ACH_COLLECTION_VIEW_TEMPLATE = "ACH_COLLECTION_VIEW_TEMPLATE";
	public static final String ACH_PAYMENT_VIEW_TEMPLATE = "ACH_PAYMENT_VIEW_TEMPLATE";
	public static final String ACH_COLLECTION_VIEW = "ACH_COLLECTION_VIEW";
	public static final String ACH_PAYMENT_VIEW = "ACH_PAYMENT_VIEW";
	public static final String BILL_PAY_VIEW_PAYMENTS = "BILL_PAY_VIEW_PAYMENTS";
	public static final String INTER_BANK_ACCOUNT_FUND_TRANSFER_VIEW = "INTER_BANK_ACCOUNT_FUND_TRANSFER_VIEW";
	public static final String INTRA_BANK_FUND_TRANSFER_VIEW = "INTRA_BANK_FUND_TRANSFER_VIEW";
	public static final String TRANSFER_BETWEEN_OWN_ACCOUNT_VIEW = "TRANSFER_BETWEEN_OWN_ACCOUNT_VIEW";
	public static final String P2P_VIEW = "P2P_VIEW";
	public static final String DOMESTIC_WIRE_TRANSFER_VIEW = "DOMESTIC_WIRE_TRANSFER_VIEW";
	public static final String INTERNATIONAL_ACCOUNT_FUND_TRANSFER_VIEW = "INTERNATIONAL_ACCOUNT_FUND_TRANSFER_VIEW";
	public static final String INTERNATIONAL_WIRE_TRANSFER_VIEW = "INTERNATIONAL_WIRE_TRANSFER_VIEW";
	public static final String ACH_COLLECTION_APPROVE = "ACH_COLLECTION_APPROVE";
	public static final String ACH_PAYMENT_APPROVE = "ACH_PAYMENT_APPROVE";
	public static final String BILL_PAY_APPROVE = "BILL_PAY_APPROVE";
	public static final String INTER_BANK_ACCOUNT_FUND_TRANSFER_APPROVE = "INTER_BANK_ACCOUNT_FUND_TRANSFER_APPROVE";
	public static final String INTRA_BANK_FUND_TRANSFER_APPROVE = "INTRA_BANK_FUND_TRANSFER_APPROVE";
	public static final String TRANSFER_BETWEEN_OWN_ACCOUNT_APPROVE = "TRANSFER_BETWEEN_OWN_ACCOUNT_APPROVE";
	public static final String P2P_APPROVE = "P2P_APPROVE";
	public static final String DOMESTIC_WIRE_TRANSFER_APPROVE = "DOMESTIC_WIRE_TRANSFER_APPROVE";
	public static final String INTERNATIONAL_ACCOUNT_FUND_TRANSFER_APPROVE = "INTERNATIONAL_ACCOUNT_FUND_TRANSFER_APPROVE";
	public static final String INTERNATIONAL_WIRE_TRANSFER_APPROVE = "INTERNATIONAL_WIRE_TRANSFER_APPROVE";
	public static final String ACH_FILE_UPLOAD = "ACH_FILE_UPLOAD";
	public static final String ACH_FILE_VIEW = "ACH_FILE_VIEW";
	public static final String ACH_FILE_APPROVE = "ACH_FILE_APPROVE";
	public static final String ACCOUNT_SETTINGS_VIEW = "ACCOUNT_SETTINGS_VIEW";
	public static final String ACCOUNT_SETTINGS_EDIT = "ACCOUNT_SETTINGS_EDIT";
	public static final String BILL_PAY_VIEW_PAYEES = "BILL_PAY_VIEW_PAYEES";
	public static final String WIRE_TRANSFERS_VIEW_PAYEES = "INTERNATIONAL_WIRE_TRANSFER_VIEW";
	public static final String BILL_PAY_CREATE_PAYEES = "BILL_PAY_CREATE_PAYEES";
	public static final String BILL_PAY_DELETE_PAYEES = "BILL_PAY_DELETE_PAYEES";
	public static final String PAYEE_MANAGEMENT_VIEW = "PAYEE_MANAGEMENT_VIEW";
	public static final String PAYEE_MANAGEMENT_CREATE = "PAYEE_MANAGEMENT_CREATE";
	public static final String PAYEE_MANAGEMENT_DELETE ="PAYEE_MANAGEMENT_DELETE";
	public static final String PAYEE_MANAGEMENT_EDIT = "PAYEE_MANAGEMENT_EDIT";
	public static final String INTER_BANK_ACCOUNT_FUND_TRANSFER_VIEW_RECEPIENT = "INTER_BANK_ACCOUNT_FUND_TRANSFER_VIEW_RECEPIENT";
	public static final String INTER_BANK_ACCOUNT_FUND_TRANSFER_CREATE_RECEPIENT = "INTER_BANK_ACCOUNT_FUND_TRANSFER_CREATE_RECEPIENT";
	public static final String INTER_BANK_ACCOUNT_FUND_TRANSFER_DELETE_RECEPIENT = "INTER_BANK_ACCOUNT_FUND_TRANSFER_DELETE_RECEPIENT";
	public static final String INTRA_BANK_FUND_TRANSFER_VIEW_RECEPIENT = "INTRA_BANK_FUND_TRANSFER_VIEW_RECEPIENT";
	public static final String INTRA_BANK_FUND_TRANSFER_CREATE_RECEPIENT = "INTRA_BANK_FUND_TRANSFER_CREATE_RECEPIENT";
	public static final String INTRA_BANK_FUND_TRANSFER_DELETE_RECEPIENT = "INTRA_BANK_FUND_TRANSFER_DELETE_RECEPIENT";
	public static final String DOMESTIC_WIRE_TRANSFER_CREATE_RECEPIENT = "DOMESTIC_WIRE_TRANSFER_CREATE_RECEPIENT";
	public static final String DOMESTIC_WIRE_TRANSFER_DELETE_RECEPIENT = "DOMESTIC_WIRE_TRANSFER_DELETE_RECEPIENT";
	public static final String INTERNATIONAL_WIRE_TRANSFER_CREATE_RECEPIENT = "INTERNATIONAL_WIRE_TRANSFER_CREATE_RECEPIENT";
	public static final String INTERNATIONAL_WIRE_TRANSFER_DELETE_RECEPIENT = "INTERNATIONAL_WIRE_TRANSFER_DELETE_RECEPIENT";
	
	public static final String BILL_PAY_ACTIVATE_OR_DEACTIVATE_EBILL = "BILL_PAY_ACTIVATE_OR_DEACTIVATE_EBILL";
	
	public static final String DOMESTIC_WIRE_TRANSFER_DELETE_BULK_TEMPLATES = "DOMESTIC_WIRE_TRANSFER_DELETE_BULK_TEMPLATES";
	public static final String DOMESTIC_WIRE_TRANSFER_UPDATE_BULK_TEMPLATES = "DOMESTIC_WIRE_TRANSFER_UPDATE_BULK_TEMPLATES";
	public static final String DOMESTIC_WIRE_TRANSFER_VIEW_BULK_TEMPLATES = "DOMESTIC_WIRE_TRANSFER_VIEW_BULK_TEMPLATES";
	public static final String INTERNATIONAL_WIRE_TRANSFER_DELETE_BULK_TEMPLATES = "INTERNATIONAL_WIRE_TRANSFER_DELETE_BULK_TEMPLATES";
	public static final String INTERNATIONAL_WIRE_TRANSFER_UPDATE_BULK_TEMPLATES = "INTERNATIONAL_WIRE_TRANSFER_UPDATE_BULK_TEMPLATES";
	public static final String INTERNATIONAL_WIRE_TRANSFER_VIEW_BULK_TEMPLATES = "INTERNATIONAL_WIRE_TRANSFER_VIEW_BULK_TEMPLATES";
	public static final String DOMESTIC_WIRE_TRANSFER_UPLOAD_BULK_FILES = "DOMESTIC_WIRE_TRANSFER_UPLOAD_BULK_FILES";
	public static final String INTERNATIONAL_WIRE_TRANSFER_UPLOAD_BULK_FILES = "INTERNATIONAL_WIRE_TRANSFER_UPLOAD_BULK_FILES";
	public static final String DOMESTIC_WIRE_TRANSFER_VIEW_RECEPIENT = "DOMESTIC_WIRE_TRANSFER_VIEW_RECEPIENT";
	public static final String INTERNATIONAL_WIRE_TRANSFER_VIEW_RECEPIENT = "INTERNATIONAL_WIRE_TRANSFER_VIEW_RECEPIENT";
	public static final String DOMESTIC_WIRE_TRANSFER_VIEW_BULK_FILES = "DOMESTIC_WIRE_TRANSFER_VIEW_BULK_FILES";
	public static final String INTERNATIONAL_WIRE_TRANSFER_VIEW_BULK_FILES = "INTERNATIONAL_WIRE_TRANSFER_VIEW_BULK_FILES";
	public static final String INTERNATIONAL_ACCOUNT_FUND_TRANSFER_VIEW_RECEPIENT = "INTERNATIONAL_ACCOUNT_FUND_TRANSFER_VIEW_RECEPIENT";
	public static final String INTERNATIONAL_ACCOUNT_FUND_TRANSFER_CREATE_RECEPIENT = "INTERNATIONAL_ACCOUNT_FUND_TRANSFER_CREATE_RECEPIENT";
	public static final String INTERNATIONAL_ACCOUNT_FUND_TRANSFER_DELETE_RECEPIENT = "INTERNATIONAL_ACCOUNT_FUND_TRANSFER_DELETE_RECEPIENT";
	public static final String P2P_CREATE_RECEPIENT="P2P_CREATE_RECEPIENT";
	public static final String P2P_DELETE_RECEPIENT="P2P_DELETE_RECEPIENT";
	
	public static final String CARD_MANAGEMENT = "CARD_MANAGEMENT";
	public static final String CARD_MANAGEMENT_ACTIVATE_CARD = "CARD_MANAGEMENT_ACTIVATE_CARD";
	public static final String CARD_MANAGEMENT_CANCEL_CARD = "CARD_MANAGEMENT_CANCEL_CARD";
	public static final String CARD_MANAGEMENT_REPORT_CARD_STOLEN = "CARD_MANAGEMENT_REPORT_CARD_STOLEN";
	public static final String CARD_MANAGEMENT_REPLACE_CARD = "CARD_MANAGEMENT_REPLACE_CARD";
	public static final String CARD_MANAGEMENT_LOCK_CARD = "CARD_MANAGEMENT_LOCK_CARD";
	public static final String CARD_MANAGEMENT_CHANGE_PIN = "CARD_MANAGEMENT_CHANGE_PIN";
	public static final String CARD_MANAGEMENT_UNLOCK_CARD = "CARD_MANAGEMENT_UNLOCK_CARD";
	public static final String CARD_MANAGEMENT_UPDATE_WITHDRAWAL = "CARD_MANAGEMENT_UPDATE_WITHDRAWAL";
	public static final String CARD_MANAGEMENT_UPDATE_PURCHASE = "CARD_MANAGEMENT_UPDATE_PURCHASE";
	public static final String CARD_MANAGEMENT_ADD_CARD_TO_APPLE_WALLET= "CARD_MANAGEMENT_ADD_CARD_APPLE_WALLET";
	public static final String CARD_MANAGEMENT_ADD_CARD_TO_GOOGLE_PAY = "CARD_MANAGEMENT_ADD_CARD_GOOGLE_PAY";
	public static final String CARD_MANAGEMENT_ADD_CARD_TO_SAMSUNG_PAY = "CARD_MANAGEMENT_ADD_CARD_SAMSUNG_PAY";
	
	public static final String BULK_PAYMENT_FILES_SINGLE_UPLOAD_CSV = "BULK_PAYMENT_FILES_SINGLE_UPLOAD_CSV";
	public static final String BULK_PAYMENT_FILES_SINGLE_UPLOAD_XML = "BULK_PAYMENT_FILES_SINGLE_UPLOAD_XML";
	public static final String BULK_PAYMENT_FILES_MULTI_UPLOAD_CSV = "BULK_PAYMENT_FILES_MULTI_UPLOAD_CSV";
	public static final String BULK_PAYMENT_FILES_MULTI_UPLOAD_XML = "BULK_PAYMENT_FILES_MULTI_UPLOAD_XML";
	public static final String BULK_PAYMENT_REQUEST_SUBMIT = "BULK_PAYMENT_REQUEST_SUBMIT";
	public static final String BULK_PAYMENT_SINGLE_SUBMIT = "BULK_PAYMENT_SINGLE_SUBMIT";
	public static final String BULK_PAYMENT_MULTIPLE_SUBMIT = "BULK_PAYMENT_MULTIPLE_SUBMIT";
	public static final String BULK_PAYMENT_FILES_VIEW = "BULK_PAYMENT_FILES_VIEW";
	public static final String BULK_PAYMENT_REQUEST_VIEW = "BULK_PAYMENT_REQUEST_VIEW";
	public static final String BULK_PAYMENT_REQUEST_CANCEL = "BULK_PAYMENT_REQUEST_CANCEL";
	public static final String BULK_PAYMENT_REQUEST_EDIT = "BULK_PAYMENT_REQUEST_EDIT";
	public static final String BULK_PAYMENT_REQUEST_APPROVE = "BULK_PAYMENT_REQUEST_APPROVE";
	public static final String BULK_PAYMENT_REQUEST_ADD_PO = "BULK_PAYMENT_REQUEST_ADD_PO";
	public static final String BULK_PAYMENT_REQUEST_EDIT_PO = "BULK_PAYMENT_REQUEST_EDIT_PO";
	public static final String BULK_PAYMENT_REQUEST_REMOVE_PO = "BULK_PAYMENT_REQUEST_REMOVE_PO";
	public static final String BULK_PAYMENT_TEMPLATE_VIEW = "BULK_PAYMENT_TEMPLATE_VIEW";
	public static final String BULK_PAYMENT_TEMPLATE_DELETE = "BULK_PAYMENT_TEMPLATE_DELETE";
	public static final String BULK_PAYMENT_TEMPLATE_EDIT = "BULK_PAYMENT_TEMPLATE_EDIT";
	
	public static final String FX_RATES_VIEW = "FX_RATES_VIEW";
	public static final String FX_RATES_VIEW_CALCULATOR = "FX_RATES_VIEW_CALCULATOR";
	
	public static final String CHEQUE_BOOK_REQUEST_CREATE = "CHEQUE_BOOK_REQUEST_CREATE";
	public static final String CHEQUE_BOOK_REQUEST_APPROVE = "CHEQUE_BOOK_REQUEST_APPROVE";
	public static final String CHEQUE_BOOK_REQUEST_VIEW = "CHEQUE_BOOK_REQUEST_VIEW";

	public static final String TRANSFER_BETWEEN_OWN_ACCOUNT_CANCEL = "TRANSFER_BETWEEN_OWN_ACCOUNT_CANCEL";
	public static final String INTERNATIONAL_ACCOUNT_FUND_TRANSFER_CANCEL = "INTERNATIONAL_ACCOUNT_FUND_TRANSFER_CANCEL";
	
	public static final String INTER_BANK_ACCOUNT_FUND_TRANSFER_CANCEL = "INTER_BANK_ACCOUNT_FUND_TRANSFER_CANCEL";
	public static final String INTRA_BANK_FUND_TRANSFER_CANCEL = "INTRA_BANK_FUND_TRANSFER_CANCEL";
	
	public static final String INTERNATIONAL_ACCOUNT_FUND_TRANSFER_CANCEL_APPROVE = "INTERNATIONAL_ACCOUNT_FUND_TRANSFER_CANCEL_APPROVE";
	public static final String INTER_BANK_ACCOUNT_FUND_TRANSFER_CANCEL_APPROVE = "INTER_BANK_ACCOUNT_FUND_TRANSFER_CANCEL_APPROVE";
	public static final String INTRA_BANK_FUND_TRANSFER_CANCEL_APPROVE = "INTRA_BANK_FUND_TRANSFER_CANCEL_APPROVE";
	public static final String TRANSFER_BETWEEN_OWN_ACCOUNT_CANCEL_APPROVE = "TRANSFER_BETWEEN_OWN_ACCOUNT_CANCEL_APPROVE";

	public static final String SIGNATORY_GROUP_CREATE_EDIT = "SIGNATORY_GROUP_CREATE_EDIT";
	public static final String SIGNATORY_GROUP_VIEW = "SIGNATORY_GROUP_VIEW";

}
